name: test-application
on:
  - push
  - pull_request
  - pull_request_review
  - issues
  - workflow_call
  - workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports:
          - "5432:5432"
        env:
          POSTGRES_PASSWORD: "password"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          architecture: "x64"
      - run: pip install pipenv && pipenv install --dev && pipenv run python -m assets.sql
      - run: pipenv run pytest app -n auto --dist load --count=10
